name = "fiscal-control-v2"
main = "worker.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "fiscal-control-v2-db"
database_id = "687d8707-248a-4ad9-82ca-07af67b82d76"

[vars]
APP_NAME = "Fiscal Control"
APP_VERSION = "2.0.0"
